project:
  type: website
  title: 'Bulk RNAseq data analysis'

website:
  site-url: 'https://hds-sandbox.github.io/bulk_RNAseq_course'
  page-navigation: true
  navbar:
    logo: develop/img/logo.png
    logo-href: http://hds-sandbox.github.io/ 
    background: primary
    left:
      - href: develop/workshop_RNAseq_nov2024.qmd
        text: Info Nov '24
      - href: develop/index.qmd
        text: Start
      - text: Experiment design
        file: develop/02_experimental_planning.qmd
      - text: Data processing
        file: develop/04a_preprocessing.qmd
      - text: Data analyses
        file: develop/05a_data_analysis_setup.qmd
      - text: "Workshop wrap-up"
        file: develop/summary.qmd
    right: 
      - icon: github
        href: https://github.com/hds-sandbox
        aria-label: GitHub
  sidebar:
    - title: "Experiment design"
      style: "docked"
      search: true
      contents:
        - develop/02_experimental_planning.qmd
        - develop/03_data_explanation.qmd
    - title: "Data processing"
      contents:
        - develop/04a_preprocessing.qmd
        - develop/04b_pipelines.qmd
        - section: "UCloud setup"
          contents: 
          - develop/04c_preprocessing_nf3170.qmd
    - title: "Data analyses"
      contents:
        - develop/05a_data_analysis_setup.qmd
        # - develop/05b_count_matrix.Rmd
        # - section: "Quality control"
        #   contents: 
        #     - develop/05c_count_normalization.Rmd
        #     - develop/06_exploratory_analysis.Rmd
        # - section: "Differential Expression"
        #   contents: 
        #     - develop/07_extra_contrast_design.Rmd
        #     - develop/07a_DEA.Rmd
        #     - develop/07b_hypothesis_testing.Rmd
        #     - develop/07c_DEA_visualization.Rmd
        # - section: "Functional Analysis"
        #   contents: 
        #     - develop/08a_FA_genomic_annotation.Rmd
        #     - develop/08b_FA_overrepresentation.Rmd
        #     - develop/08c_FA_GSEA.Rmd
        # - section: "Workflow summary"
        #   contents: 
        #     - develop/09_summarized_workflow.Rmd
format:
  html:
    theme: 
      light: [materia, css/materialight.scss]
      dark: darkly
    toc: true
    code-fold: true

filters:
  - css/custom-callout.lua
